#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

wget https://github.com/wildlife-systems/pi-pwr/raw/master/pi-pwr
chown root:root pi-pwr
chmod +x pi-pwr
mv pi-pwr /usr/bin
